package org.apeiron.kernel.domain.enumeration;

/**
 * The MenuElement enumeration.
 */
public enum MenuElement {
    DATOS_GENERALES,
    DATOS_PROPUESTA,
    DATOS_PROYECTO,
    BENEFICIARIO,
    PARTICIPANTES,
    PLAN_TRABAJO,
    DESGLOSE_FINANCIERO,
    EVALUADORES,
    DOCUMENTOS,
    AYUDANTE,
    SITUACION_ACTUAL,
    INFORME_MENSUAL,
    ACREDITACION,
    ACREDITACION_SIN_INSTITUCION,
    DECLARACION_VERACIDAD,
    DICTAMEN,
    EVALUACION_INDIVIDUAL,
    EVALUACION_PLENARIA,
    EVALUACIONES_INDIVIDUALES,
    DICTAMEN_PLENO,
    MATRICULA,
    PROGRAMA,
    EVALUACION_CONSEJO,
    RECONSIDERACION,
    RESULTADO_RECONSIDERACION,
    RESULTADO,
    INSTITUCION,
    BUSCADOR,
    REGLAS_PAGO,
    PADRON,
    INVESTIGADOR,
    MOVIMIENTO,
    HISTORICO_PAGOS,
    REVISORES,
    CONCILIACION
}
